#!/usr/bin/env bash

set -euo pipefail

# Install Python dependencies
pip3 install requests
#IFS=',' read -r -a secret_keys <<< "${SECRET_KEYS}"
# Run the Python script to retrieve secrets
python3 ${BUILDKITE_PLUGINS_PATH}/github-com-muntashir-islam-azure-keyvault-buildkite-plugin-python-git-v3-0-1/get_secrets_azure.py "${SECRET_KEYS}" 
#python3 get_secrets_azure.py "Muntashir,work"
