#!/usr/bin/env bash

set -euo pipefail

# Install Python dependencies
pip install requests

# Run the Python script to retrieve secrets
python get_secrets_azure.py "${BUILDKITE_SECRETS}" > secrets.env